[package]
name = "tui-widget-list"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
ratatui = "0.24"
unicode-width = "0.1"
textwrap = "0.16.0"

[dev-dependencies]
anyhow = "1.0.71"

[[example]]
name = "widget_list"